python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test0.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test1.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test2.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test3.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test4.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test5.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test6.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test7.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test8.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test9.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test10.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test11.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test12.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test13.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test14.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test15.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test16.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test17.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test18.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test19.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test20.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test21.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test22.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test23.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test24.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test25.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test26.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test27.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test28.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test29.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test30.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test31.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test32.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test33.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test34.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test35.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test36.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test37.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test38.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test39.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test40.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test41.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test42.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test43.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test44.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test45.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test46.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test47.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test48.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test49.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test50.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test51.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test52.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test53.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test54.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test55.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test56.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test57.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test58.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test59.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test60.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test61.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test62.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test63.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test64.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test65.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test66.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test67.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test68.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test69.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test70.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test71.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test72.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test73.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test74.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test75.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test76.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test77.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test78.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test79.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test80.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test81.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test82.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test83.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test84.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test85.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test86.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test87.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test88.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test89.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test90.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test91.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test92.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test93.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test94.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test95.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test96.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test97.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test98.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test99.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test100.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test101.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test102.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test103.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test104.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test105.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test106.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test107.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test108.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test109.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test110.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test111.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test112.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test113.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test114.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test115.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test116.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test117.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test118.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test119.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test63.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test121.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test122.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test123.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test124.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test125.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test126.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test127.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test128.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test129.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test130.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test131.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test132.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test133.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test134.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test135.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test136.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test137.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test138.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test139.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test140.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test141.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test142.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test143.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test144.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test145.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test146.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test147.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test148.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test149.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test150.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test151.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test152.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test153.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test154.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test155.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test156.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test157.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test158.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test159.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test160.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test161.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test162.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test163.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test164.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test165.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test166.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test167.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test168.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test169.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test170.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test171.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test172.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test173.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test174.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test175.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test176.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test177.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test178.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test179.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test180.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test181.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test182.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test183.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test184.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test185.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test186.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test187.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test188.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test189.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test190.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test191.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test192.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test193.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test194.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test195.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test196.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test197.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test198.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test199.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test200.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test201.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test202.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test203.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test204.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test205.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test206.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test207.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test208.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test209.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test210.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test211.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test212.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test213.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test214.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test215.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test216.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test217.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test218.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test219.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test220.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test221.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test222.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test223.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test224.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test225.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test226.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test227.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test228.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test229.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test230.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test231.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test232.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test233.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test234.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test235.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test236.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test237.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test238.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test239.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test240.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test241.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test242.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test243.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test244.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test245.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test246.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test247.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test248.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test249.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test250.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test251.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test252.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test253.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test254.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test255.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test256.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test257.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test258.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test259.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test260.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test261.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test262.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test263.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test264.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test265.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test266.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test267.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test268.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test269.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test270.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test271.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test272.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test273.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test274.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test275.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test276.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test277.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test278.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test279.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test280.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test281.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test282.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test283.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test284.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test285.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test286.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test287.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test288.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test289.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test290.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test291.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test292.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test293.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test294.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test295.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test296.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test297.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test298.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test299.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test300.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test301.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test302.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test303.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test304.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test305.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test306.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test307.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test308.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test309.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test310.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test311.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test312.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test313.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test314.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test315.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test316.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test317.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test318.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test319.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test320.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test321.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test322.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test323.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test324.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test325.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test326.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test327.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test328.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test329.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test330.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test331.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test332.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test333.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test334.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test335.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test336.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test337.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test338.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test339.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test340.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test341.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test342.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test343.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test344.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test345.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test346.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test347.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test348.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test349.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test350.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test351.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test352.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test353.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test354.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test355.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test356.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test357.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test358.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test359.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test360.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test361.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test362.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test363.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test364.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test365.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test366.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test367.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test368.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test369.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test370.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test371.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test372.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test373.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test374.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test375.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test376.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test377.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test378.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test379.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test380.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test381.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test382.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test383.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test384.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test385.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test386.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test387.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test388.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test389.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test390.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test391.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test392.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test393.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test394.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test395.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test396.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test397.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test398.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test399.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test400.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test401.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test402.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test403.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test404.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test405.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test406.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test407.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test408.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test409.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test410.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test411.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test412.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test413.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test414.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test415.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test416.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test417.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test418.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test419.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test420.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test421.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test422.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test423.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test424.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test425.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test426.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test427.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test428.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test429.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test430.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test431.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test432.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test433.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test434.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test435.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test436.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test437.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test438.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test439.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test440.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test441.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test442.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test443.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test444.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test445.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test446.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test447.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test448.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test449.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test450.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test451.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test452.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test453.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test454.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test455.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test456.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test457.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test458.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test459.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test460.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test461.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test462.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test463.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test464.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test465.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test466.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test467.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test468.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test469.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test470.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test471.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test472.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test473.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test474.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test475.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test476.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test477.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test478.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test479.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test480.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test481.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test482.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test483.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test484.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test485.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test486.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test487.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test488.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test489.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test490.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test491.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test492.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test493.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test494.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test495.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test496.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test497.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test498.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test499.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test500.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test501.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test502.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test503.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test504.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test505.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test506.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test507.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test508.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test509.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test510.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test511.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test512.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test513.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test514.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test515.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test516.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test517.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test518.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test519.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test520.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test521.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test522.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test523.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test524.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test525.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test526.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test527.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test528.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test529.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test530.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test531.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test532.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test533.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test534.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test535.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test536.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test537.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test538.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test539.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test540.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test541.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test542.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test543.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test544.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test545.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test546.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test547.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test548.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test549.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test550.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test551.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test552.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test553.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test554.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test555.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test556.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test557.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test558.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test559.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test560.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test561.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test562.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test563.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test564.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test565.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test566.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test567.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test568.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test569.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test570.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test571.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test572.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test573.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test574.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test575.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test576.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test577.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test578.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test579.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test580.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test581.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test582.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test583.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test584.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test585.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test586.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test587.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test588.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test589.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test590.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test591.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test592.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test593.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test594.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test595.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test596.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test597.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test598.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test599.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test600.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test601.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test602.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test603.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test604.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test605.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test606.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test607.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test608.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test609.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test610.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test611.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test612.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test613.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test614.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test615.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test616.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test617.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test618.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test619.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test620.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test621.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test622.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test623.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test624.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test625.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test626.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test627.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test628.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test629.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test630.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test631.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test632.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test633.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test634.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test635.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test636.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test637.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test638.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test639.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test640.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test641.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test642.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test643.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test644.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test645.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test646.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test647.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test648.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test649.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test650.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test651.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test652.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test653.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test654.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test655.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test656.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test657.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test658.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test659.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test660.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test661.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test662.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test663.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test664.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test665.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test666.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test667.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test668.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test669.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test670.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test671.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test672.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test673.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test674.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test675.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test676.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test677.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test678.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test679.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test680.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test681.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test682.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test683.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test684.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test685.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test686.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test687.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test688.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test689.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test690.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test691.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test692.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test693.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test694.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test695.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test696.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test697.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test698.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test699.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test700.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test701.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test702.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test703.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test704.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test705.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test706.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test707.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test708.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test709.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test710.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test711.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test712.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test713.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test714.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test715.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test716.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test717.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test718.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test719.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test720.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test721.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test722.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test723.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test724.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test725.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test726.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test727.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test728.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test729.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test730.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test731.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test732.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test733.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test734.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test735.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test736.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test737.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test738.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test739.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test740.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test741.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test742.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test743.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test744.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test745.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test746.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test747.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test748.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test749.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test750.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test751.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test752.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test753.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test754.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test755.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test756.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test757.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test758.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test759.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test760.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test761.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test762.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test763.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test764.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test765.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test766.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test767.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test768.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test769.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test770.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test771.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test772.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test773.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test774.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test775.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test776.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test777.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test778.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test779.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test780.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test781.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test782.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test783.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test784.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test785.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test786.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test787.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test788.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test789.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test790.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test791.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test792.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test793.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test794.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test795.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test796.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test797.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test798.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test799.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test800.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test801.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test802.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test803.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test804.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test805.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test806.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test807.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test808.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test809.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test810.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test811.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test812.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test813.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test814.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test815.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test816.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test817.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test818.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test819.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test820.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test821.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test822.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test823.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test824.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test825.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test826.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test827.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test828.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test829.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test830.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test831.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test832.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test833.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test834.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test835.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test836.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test837.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test838.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test839.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test840.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test841.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test842.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test843.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test844.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test845.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test846.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test847.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test848.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test849.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test850.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test851.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test852.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test853.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test854.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test855.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test856.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test857.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test858.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test859.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test860.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test861.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test862.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test863.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test864.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test865.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test866.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test867.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test868.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test869.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test870.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test871.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test872.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test873.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test874.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test875.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test876.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test877.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test878.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test879.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test880.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test881.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test882.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test883.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test884.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test885.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test886.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test887.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test888.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test889.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test890.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test891.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test892.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test893.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test894.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test895.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test896.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test897.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test898.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test899.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test900.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test901.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test902.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test903.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test904.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test905.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test906.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test907.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test908.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test909.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test910.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test911.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test912.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test913.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test914.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test915.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test916.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test917.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test918.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test919.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test920.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test921.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test922.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test923.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test924.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test925.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test926.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test927.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test928.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test929.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test930.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test931.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test932.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test933.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test934.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test935.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test936.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test937.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test938.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test939.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test940.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test941.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test942.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test943.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test944.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test945.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test946.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test947.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test948.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test949.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test950.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test951.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_180/test952.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_180/test953.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test954.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test955.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test956.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test957.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test958.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test959.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test960.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test961.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test962.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test963.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test964.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test965.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test966.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test967.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test968.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test969.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test970.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test971.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test972.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test973.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test974.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test975.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test976.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test977.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test978.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test979.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test980.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test981.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test982.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test983.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test984.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test985.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test986.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test987.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test988.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test989.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test990.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test991.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test992.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test993.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test994.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test995.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test996.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test997.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test998.txt
python3 approximation_solution/cs412_approx.py < test_cases/test_cases_forGraph_63/test999.txt