python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test0.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test1.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test2.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test3.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test4.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test5.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test6.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test7.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test8.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test9.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test10.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test11.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test12.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test13.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test14.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test15.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test16.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test17.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test18.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test19.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test20.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test21.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test22.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test23.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test24.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test25.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test26.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test27.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test28.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test29.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test30.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test31.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test32.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test33.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test34.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test35.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test36.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test37.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test38.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test39.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test40.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test41.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test42.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test43.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test44.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test45.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test46.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test47.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test48.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test49.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test50.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test51.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test52.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test53.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test54.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test55.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test56.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test57.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test58.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test59.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test60.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test61.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test62.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test63.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test64.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test65.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test66.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test67.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test68.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test69.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test70.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test71.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test72.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test73.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test74.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test75.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test76.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test77.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test78.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test79.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test80.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test81.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test82.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test83.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test84.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test85.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test86.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test87.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test88.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test89.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test90.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test91.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test92.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test93.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test94.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test95.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test96.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test97.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test98.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test99.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test100.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test101.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test102.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test103.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test104.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test105.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test106.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test107.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test108.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test109.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test110.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test111.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test112.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test113.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test114.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test115.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test116.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test117.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test118.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test119.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test120.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test121.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test122.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test123.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test124.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test125.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test126.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test127.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test128.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test129.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test130.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test131.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test132.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test133.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test134.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test135.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test136.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test137.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test138.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test139.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test140.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test141.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test142.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test143.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test144.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test145.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test146.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test147.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test148.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test149.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test150.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test151.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test152.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test153.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test154.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test155.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test156.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test157.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test158.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test159.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test160.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test161.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test162.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test163.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test164.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test165.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test166.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test167.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test168.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test169.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test170.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test171.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test172.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test173.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test174.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test175.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test176.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test177.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test178.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test179.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test180.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test181.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test182.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test183.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test184.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test185.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test186.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test187.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test188.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test189.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test190.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test191.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test192.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test193.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test194.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test195.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test196.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test197.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test198.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test199.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test200.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test201.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test202.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test203.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test204.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test205.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test206.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test207.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test208.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test209.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test210.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test211.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test212.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test213.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test214.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test215.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test216.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test217.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test218.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test219.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test220.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test221.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test222.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test223.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test224.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test225.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test226.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test227.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test228.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test229.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test230.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test231.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test232.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test233.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test234.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test235.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test236.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test237.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test238.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test239.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test240.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test241.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test242.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test243.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test244.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test245.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test246.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test247.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test248.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test249.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test250.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test251.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test252.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test253.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test254.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test255.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test256.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test257.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test258.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test259.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test260.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test261.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test262.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test263.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test264.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test265.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test266.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test267.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test268.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test269.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test270.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test271.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test272.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test273.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test274.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test275.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test276.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test277.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test278.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test279.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test280.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test281.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test282.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test283.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test284.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test285.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test286.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test287.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test288.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test289.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test290.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test291.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test292.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test293.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test294.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test295.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test296.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test297.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test298.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test299.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test300.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test301.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test302.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test303.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test304.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test305.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test306.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test307.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test308.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test309.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test310.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test311.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test312.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test313.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test314.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test315.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test316.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test317.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test318.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test319.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test320.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test321.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test322.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test323.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test324.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test325.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test326.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test327.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test328.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test329.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test330.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test331.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test332.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test333.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test334.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test335.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test336.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test337.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test338.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test339.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test340.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test341.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test342.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test343.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test344.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test345.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test346.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test347.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test348.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test349.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test350.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test351.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test352.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test353.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test354.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test355.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test356.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test357.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test358.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test359.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test360.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test361.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test362.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test363.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test364.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test365.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test366.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test367.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test368.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test369.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test370.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test371.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test372.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test373.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test374.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test375.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test376.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test377.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test378.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test379.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test380.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test381.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test382.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test383.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test384.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test385.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test386.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test387.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test388.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test389.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test390.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test391.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test392.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test393.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test394.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test395.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test396.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test397.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test398.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test399.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test400.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test401.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test402.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test403.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test404.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test405.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test406.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test407.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test408.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test409.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test410.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test411.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test412.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test413.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test414.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test415.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test416.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test417.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test418.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test419.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test420.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test421.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test422.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test423.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test424.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test425.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test426.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test427.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test428.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test429.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test430.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test431.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test432.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test433.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test434.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test435.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test436.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test437.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test438.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test439.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test440.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test441.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test442.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test443.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test444.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test445.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test446.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test447.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test448.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test449.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test450.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test451.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test452.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test453.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test454.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test455.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test456.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test457.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test458.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test459.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test460.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test461.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test462.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test463.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test464.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test465.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test466.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test467.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test468.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test469.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test470.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test471.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test472.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test473.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test474.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test475.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test476.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test477.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test478.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test479.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test480.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test481.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test482.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test483.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test484.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test485.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test486.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test487.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test488.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test489.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test490.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test491.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test492.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test493.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test494.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test495.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test496.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test497.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test498.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test499.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test500.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test501.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test502.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test503.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test504.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test505.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test506.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test507.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test508.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test509.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test510.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test511.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test512.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test513.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test514.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test515.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test516.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test517.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test518.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test519.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test520.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test521.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test522.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test523.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test524.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test525.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test526.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test527.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test528.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test529.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test530.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test531.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test532.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test533.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test534.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test535.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test536.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test537.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test538.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test539.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test540.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test541.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test542.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test543.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test544.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test545.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test546.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test547.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test548.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test549.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test550.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test551.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test552.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test553.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test554.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test555.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test556.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test557.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test558.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test559.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test560.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test561.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test562.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test563.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test564.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test565.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test566.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test567.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test568.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test569.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test570.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test571.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test572.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test573.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test574.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test575.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test576.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test577.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test578.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test579.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test580.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test581.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test582.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test583.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test584.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test585.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test586.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test587.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test588.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test589.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test590.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test591.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test592.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test593.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test594.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test595.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test596.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test597.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test598.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test599.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test600.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test601.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test602.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test603.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test604.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test605.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test606.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test607.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test608.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test609.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test610.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test611.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test612.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test613.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test614.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test615.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test616.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test617.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test618.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test619.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test620.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test621.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test622.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test623.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test624.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test625.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test626.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test627.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test628.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test629.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test630.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test631.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test632.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test633.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test634.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test635.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test636.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test637.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test638.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test639.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test640.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test641.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test642.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test643.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test644.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test645.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test646.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test647.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test648.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test649.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test650.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test651.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test652.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test653.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test654.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test655.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test656.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test657.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test658.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test659.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test660.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test661.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test662.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test663.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test664.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test665.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test666.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test667.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test668.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test669.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test670.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test671.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test672.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test673.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test674.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test675.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test676.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test677.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test678.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test679.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test680.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test681.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test682.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test683.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test684.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test685.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test686.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test687.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test688.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test689.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test690.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test691.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test692.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test693.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test694.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test695.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test696.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test697.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test698.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test699.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test700.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test701.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test702.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test703.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test704.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test705.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test706.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test707.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test708.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test709.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test710.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test711.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test712.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test713.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test714.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test715.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test716.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test717.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test718.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test719.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test720.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test721.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test722.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test723.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test724.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test725.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test726.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test727.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test728.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test729.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test730.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test731.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test732.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test733.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test734.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test735.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test736.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test737.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test738.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test739.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test740.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test741.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test742.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test743.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test744.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test745.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test746.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test747.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test748.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test749.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test750.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test751.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test752.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test753.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test754.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test755.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test756.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test757.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test758.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test759.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test760.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test761.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test762.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test763.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test764.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test765.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test766.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test767.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test768.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test769.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test770.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test771.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test772.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test773.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test774.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test775.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test776.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test777.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test778.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test779.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test780.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test781.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test782.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test783.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test784.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test785.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test786.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test787.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test788.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test789.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test790.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test791.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test792.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test793.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test794.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test795.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test796.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test797.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test798.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test799.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test800.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test801.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test802.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test803.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test804.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test805.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test806.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test807.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test808.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test809.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test810.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test811.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test812.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test813.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test814.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test815.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test816.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test817.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test818.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test819.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test820.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test821.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test822.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test823.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test824.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test825.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test826.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test827.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test828.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test829.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test830.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test831.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test832.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test833.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test834.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test835.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test836.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test837.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test838.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test839.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test840.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test841.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test842.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test843.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test844.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test845.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test846.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test847.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test848.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test849.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test850.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test851.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test852.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test853.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test854.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test855.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test856.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test857.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test858.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test859.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test860.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test861.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test862.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test863.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test864.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test865.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test866.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test867.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test868.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test869.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test870.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test871.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test872.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test873.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test874.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test875.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test876.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test877.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test878.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test879.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test880.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test881.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test882.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test883.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test884.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test885.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test886.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test887.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test888.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test889.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test890.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test891.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test892.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test893.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test894.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test895.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test896.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test897.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test898.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test899.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test900.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test901.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test902.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test903.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test904.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test905.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test906.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test907.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test908.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test909.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test910.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test911.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test912.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test913.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test914.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test915.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test916.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test917.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test918.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test919.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test920.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test921.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test922.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test923.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test924.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test925.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test926.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test927.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test928.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test929.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test930.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test931.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test932.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test933.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test934.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test935.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test936.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test937.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test938.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test939.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test940.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test941.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test942.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test943.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test944.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test945.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test946.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test947.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test948.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test949.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test950.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test951.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test952.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test953.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test954.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test955.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test956.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test957.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test958.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test959.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test960.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test961.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test962.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test963.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test964.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test965.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test966.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test967.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test968.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test969.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test970.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test971.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test972.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test973.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test974.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test975.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test976.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test977.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test978.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test979.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test980.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test981.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test982.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test983.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test984.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test985.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test986.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test987.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test988.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test989.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test990.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test991.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test992.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test993.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test994.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test995.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test996.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test997.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test998.txt
python3 exact_solution/cs412_exact.py < exact_solution/test_cases/test_cases_forGraph/test999.txt